### ISSUE TITLE
Upload to CurseForge

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [cschierig/AdvancementDisable#1]
Hey, would you mind uploading this to CF as-well?

If not, would you mind if I upload a fork? It's exactly what I need and don't wanna recode it to just be able to upload it to CF.

**Comment by cschierig** [comment]
I can do that, but I probably won't have the time until next Saturday.

**Comment by 3x1t-5tyl3** [comment]
Awesome! TYT. No rush <3

**Comment by cschierig** [comment]
Once approved, you can find it here:
https://legacy.curseforge.com/minecraft/mc-mods/advancementdisable
